services:
  bot:
    build:
      dockerfile: docker/bot/Dockerfile
    working_dir: /srv
    volumes:
      - .:/srv
  sync:
    build:
      dockerfile: docker/synchronizer/Dockerfile
    working_dir: /srv
    volumes:
      - .:/srv